apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: jigyasumishra321/nginx
        ports:
        - containerPort: 80
        
                
---

kind: Service
apiVersion: v1
metadata:
  name: hello-world
  namespace: default

spec:
 

  type: NodePort

  selector:

     app: tomcat

  ports:

   - name: http

     protocol: "TCP"

     port: 8080

     targetPort: 80
    
